name: Index plan files

permissions:
  contents: write

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Index YAML plans into a single json
        uses: ./.github/actions/index_plans
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: index_plans

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan_index
          path: 'index.json'
          overwrite: true

